jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        continue-on-error: true

      - name: Handle Failure
        if: failure()
        run: echo "Terraform apply failed"